### ISSUE TITLE
Duplication of recent entries

### ISSUE THREAD

**Issue by peter-gb** [KeshiaRose/Toggl-Web-Data-Connector#5]
This * may * be an issue with my account but I don't know how to check.
I get two rows per Entry ID for the 50 most recent entries.
The Entry IDs are still unique but it looks like there are 2 identical records for these 50

![image](https://user-images.githubusercontent.com/43183973/130619075-ea906cad-ab01-467e-924d-c33452c8dbbb.png)

**Comment by KeshiaRose** [comment]
Sorry for the delayed response! I'm not able to reproduce the duplicate entries. Is there anything you can think of that changed for your account recently?

**Comment by musilda2** [comment]
Hi Keshia, 

thank you very much for the connector. I tried it for the very first time.
However, I ran into the same problem as Peter. The most recent 50 rows with Unique Entry ID are duplicated.

**Comment by KeshiaRose** [comment]
Interesting, does it start around the same time for you too? August 21? I wonder if something changed with the API or the way Toggl is delivering the data. Also, are you using billing, clients, tags etc? Also, are the rows exactly identical?

**Comment by peter-gb** [comment]
Hey Keshia, just wanted to update you - the issue is still there with my account. It is the most recent 50 entries still, so the entry IDs which were previously duplicated now are not, and the new duplicates are literally the 50 most recent. The duplicate rows have two instances per entry ID in every case, and the values for the duplicates are identical for every field.

For my purposes I've fixed the visualisation element by using a calc, { FIXED [Entry ID] : AVG([Duration (Seconds)]) }

However, it's a workaround to make the viz look ok, not a fix.
Here's my set up - it's pulling around 3000 entries in total.
![image](https://user-images.githubusercontent.com/43183973/135642974-23f29232-d43e-4795-b840-92abc46fa51e.png)

It's not a major issue for me now I'm using the calc but it's still there.
Thanks for building this btw, such a good wdc!

**Comment by KeshiaRose** [comment]
Aha! That helps, I have no idea why this stopped working all of a sudden, maybe it never worked and it just went unnoticed? 🤷🏾‍♀️  Looks like I was doing some really weird looping and pulled in the last page of data twice each time. The fact that you said it was a different 50 is what made me realize what was going on. Just made an update, let me know if it fixes things for you!

**Comment by peter-gb** [comment]
That's great - all working perfectly now, thank you !
