### ISSUE TITLE
Task ID is Null

### ISSUE THREAD

**Issue by peter-gb** [KeshiaRose/Toggl-Web-Data-Connector#6]
Hey Keshia, 

Sill loving this and using it every week! I noticed that the Task ID has become null, any ideas?

Thanks, Peter

**Comment by KeshiaRose** [comment]
Hey Peter, 🙂

Unfortunately, it looks like Toggl has completely changed its API in the latest version which makes updating this more than trivial. I already spent maybe an hour going through and trying to figure it out (after already spending time refactoring the code a bit 😥). They no longer provide everything in one request, so you need to pull in projects, clients, tasks, and tags separately. While this complicates things quite a bit, it wouldn't be so bad. However, then I realized they added CORS restrictions that will prevent this WDC from running purely in the front end as it does today. This means I would have to find somewhere to host a back end which would likely mean paying money to do so. Therefore, after trying a bunch of things, I don't think it would be feasible for me to make such major updates to this WDC. (I don't even use Toggl anymore). Toggl has a lot of integrations available, way more than when I first made this. Perhaps there is something available that you can use to pull this data in? Sorry that this is the response, I truly tried to make this work.

\- Keshia

**Comment by peter-gb** [comment]
Ahhh Keshia I’m so sorry you had to spend so much time on it! I’d hoped it was a fairly simple thing but an innocuous ‘null ID’ can turn into such a nightmare!

Thanks so much for your efforts anyway, I hope this continues to work as I love using toggl! Still appreciate you developing this. I ought to learn how to do such things myself!

All the best anyhow and thanks for the great efforts in making this in the first place!

Best

Peter GB

On 25 Jan 2023, at 01:50, Keshia Rose ***@***.***> wrote:

﻿

Hey Peter, 🙂

Unfortunately, it looks like Toggl has completely changed its API in the latest version which makes updating this more than trivial. I already spent maybe an hour going through and trying to figure it out (after already spending time refactoring the code a bit 😥). They no longer provide everything in one request, so you need to pull in projects, clients, tasks, and tags separately. While this complicates things quite a bit, it wouldn't be so bad. However, then I realized they added CORS restrictions that will prevent this WDC from running purely in the front end as it does today. This means I would have to find somewhere to host a back end which would likely mean paying money to do so. Therefore, after trying a bunch of things, I don't think it would be feasible for me to make such major updates to this WDC. (I don't even use Toggl anymore). Toggl has a lot of integrations available, way more than when I first made this. Perhaps there is something available that you can use to pull this data in? Sorry that this is the response, I truly tried to make this work.

  *   Keshia

**Comment by KeshiaRose** [comment]
Thanks Peter, 🙂 I hope it keeps working for a long time!
